package com.wsxdev.simuladorcircuitos.vista;

import com.liferay.portal.kernel.security.pwd.Toolkit;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

import com.wsxdev.simuladorcircuitos.vista.PanelCircuito;
import com.wsxdev.simuladorcircuitos.controlador.CircuitoControlador;


public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    private JToolBar toolBar;
    private JPanel menuLateral;
    private JButton botonBurger;
    private JButton btnInicio, btnNuevo, btnAgregar, btnConectar, btnSimular, btnGuardar;
    private JPanel panelCentral;
    private PanelCircuito panelCircuito;
    private CircuitoControlador controlador = new CircuitoControlador();



    public MainWindow() {
        initComponents();

        setTitle("Simulador de Circuitos");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        // setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        // setResizable(false);
        pack();
        panelCircuito = new PanelCircuito();
        panelCircuito.setBounds(220, 0, getWidth() - 220, getHeight());
        getContentPane().add(panelCircuito);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setLayout(new BorderLayout());

        // ToolBar superior
        toolBar = new JToolBar();
        toolBar.setFloatable(false);
        botonBurger = new JButton(new ImageIcon(getClass().getResource("/img/png/iconMenus/menu-burger.png")));
        botonBurger.addActionListener(e -> menuLateral.setVisible(!menuLateral.isVisible()));
        toolBar.add(botonBurger);
        add(toolBar, BorderLayout.NORTH);

        // Menú lateral
        menuLateral = new JPanel();
        menuLateral.setLayout(new GridLayout(6, 1, 10, 10));
        menuLateral.setPreferredSize(new Dimension(200, 0));

        btnInicio = new JButton("Inicio");
        btnNuevo = new JButton("Nuevo circuito");
        btnAgregar = new JButton("Agregar componente");
        btnConectar = new JButton("Conectar");
        btnSimular = new JButton("Simular");
        btnGuardar = new JButton("Guardar");

        btnGuardar.addActionListener(e -> {
            if (panelCircuito != null) {
                controlador.guardarCircuito(panelCircuito.obtenerCircuitoComoModelo());
                JOptionPane.showMessageDialog(this, "Circuito guardado exitosamente.");
            }
        });


        menuLateral.add(btnInicio);
        menuLateral.add(btnNuevo);
        menuLateral.add(btnAgregar);
        menuLateral.add(btnConectar);
        menuLateral.add(btnSimular);
        menuLateral.add(btnGuardar);

        add(menuLateral, BorderLayout.WEST);

        // Panel Central (área de dibujo o contenido dinámico)
        panelCentral = new JPanel();
        panelCentral.setBackground(Color.WHITE);
        panelCentral.setLayout(null); // Para control absoluto
        add(panelCentral, BorderLayout.CENTER);
    }  // </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new MainWindow().setVisible(true));
    }
    /**
     * @param args the command line arguments
     */

    /*public static void main(String args[]) {
        // Set the Nimbus look and feel
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}